version: "3.9"

services:

  web:
    container_name: petition-back
    build: ./
    ports:
      - "8000:8000"
    restart: always
    entrypoint: /entrypoint.sh
    volumes:
      - ./:/web
      - static_volume:/web/static
    depends_on:
      - db
    command: ["healthy-check.sh", "db:5432"]


  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    ports:
      - 80:80
#    depends_on:
#      - server

  redis:
    image: "redis:alpine"

volumes:
  static_volume:
  postgres_data:
